README.md

In support of [documenting steps that were tucked away](https://github.com/n-riesco/jmp/pull/12#issuecomment-199823632).
/cc @n-riesco

Provide release steps

---

README.md

Good for devs and such.
Closes #13.

Update README with dev install

---

binding.gyp
build.js
package.json

Add static library bindings for OS X

---

appveyor.yml
binding.cc
binding.gyp
lib/index.js
windows/lib/x64/libzmq-v100-mt-4_0_4.dll
windows/lib/x64/libzmq-v100-mt-4_0_4.lib
windows/lib/x64/libzmq.dll
windows/lib/x64/libzmq.lib
windows/lib/x86/libzmq-v100-mt-4_0_4.dll
windows/lib/x86/libzmq-v100-mt-4_0_4.lib
windows/lib/x86/libzmq.dll
windows/lib/x86/libzmq.lib
windows/smoketest.js

x86 builds don't seem to work, nor do debug builds. Not sure why either fails.
Build completes now, but there appears to be a crash when trying to send messages.
At least the DLL gets loaded.

build x64 release builds on appveyor

---

Dockerfile
README.md

Doing some cleanup before a release.

Rely on zmq script not hash

---

.travis.yml
build_libzmq.sh

caused by deprecated [`--with-tweetnacl` flag](https://travis-ci.org/nteract/zmq-prebuilt/jobs/158793824#L365)

Fix build warning

---

.travis.yml
README.md
package.json

Travis for the win 🎉 
Tested on my [fork](https://github.com/lgeiger/zmq-prebuilt/releases/tag/v1.2.3).

Deploy prebuilds with travis

---

appveyor.yml

Windooows [prebuilts](https://github.com/lgeiger/zmq-prebuilt/releases/tag/v1.2.4)!
Closes #34

Deploy prebuilds with appveyor

---

README.md

Update installation and release instructions

---

README.md
build_libzmq.sh
download-zmq.js

Accidentally moved from #61 
Closes #60

Use Node to download zeromq vs. wget

---

.gitattributes
.gitignore
README.md
binding.gyp
scripts/download-win-lib.js
scripts/download-zmq.js
scripts/download.js
windows/lib/Win32/libzmq.lib
windows/lib/x64/libzmq.lib

Download windows library from github releases

---

scripts/download-win-lib.js

Store windows lib in different repo

---

.gitignore
.travis.yml
README.md
codecov.yml
package.json

Since we heavily rely on CI it's interesting to know what the test coverage is.

Hello codecov

---

README.md
package.json

Update package.json and README

---

appveyor.yml

Update Appveyor upload token

---

.travis.yml
appveyor.yml

Let's see if we get any notifications to the zmq-prebuilt channel at http://slack.nteract.in/

CI notifications

---

appveyor.yml

AppVeyor: Fix indentation

---

codecov.yml
scripts/publish_docs.sh

Another PR to clean up our CI setup

Travis: Only deploy docs on linux build

---

.travis.yml
appveyor.yml
scripts/publish_docs.sh

This PR will reduce the build matrix, simplify the build scripts and therefor speed up the builds.
Originally I had in mind to setup a 32-bit Linux build. But we would need to do the builds inside a docker container which I'm not familiar with.

Simplify CI builds

---

scripts/preinstall.js

Adresses #94 until we find a better solution

Use libzmq 4.1.6 on linux

---

scripts/download.js

* Use ES5 in `scripts/dowload.js`

Fix compatibility with older Node versions

---

.travis.yml
appveyor.yml
package.json

Bring in https://github.com/mafintosh/prebuild/pull/135

Bump prebuild@4.5.0 and dev-deps

---

package.json

https://github.com/mafintosh/prebuild/pull/141 🎉

Support prebuilts for Electron

---

README.md

Update install instructions for Electron

---

README.md

Explain use of electron-builder with zeromq.js

---

scripts/build_libzmq.sh

* This change reduces build times by half.

Build libzmq without documentation

---

binding.cc
lib/index.js
test/socket.monitor.js
test/socket.pub-sub.js

* Includes https://github.com/JustinTulloss/zeromq.node/pull/575
* Includes https://github.com/JustinTulloss/zeromq.node/pull/578

Merge upstream

---

README.md

Provide background on zeromq.js

---

scripts/download.js
scripts/preinstall.js

In light of https://github.com/nteract/hydrogen/issues/292#issuecomment-303726903, I figured we could provide some human friendly output on error in the downloader. The handles _one_ of the `https` calls, which would be the initial one.

Refactor preinstall

---

binding.cc
lib/index.js

https://github.com/zeromq/zeromq.js/issues/146

Add ZMQ_ROUTER_HANDOVER option

---

.travis.yml
scripts/preinstall.js

Fix https://github.com/zeromq/zeromq.js/issues/94 & https://github.com/zeromq/zeromq.js/issues/151

Change compiler to be able to use libzmq 4.2

---

.travis.yml

We need to change the OS also on the test branch. https://github.com/zeromq/zeromq.js/issues/94

Change test OS to Ubuntu 14.04 LTS

---

lib/index.js

* Fix multipart messages for xpub/xsub

Fix multipart messages for xpub/xsub (#593)

---

scripts/prebuild-install.js

It won't download any prebuilds atm.

Fix path error in npm installation

---

.travis.yml
package-lock.json
package.json

We should commit the package-lock.json since npm@5
[package-lock.json | npm Documentation](https://docs.npmjs.com/files/package-lock.json)

Add package-lock.json and tell greenkeeper to update it

---

.travis.yml

Clean up travis.yml because of bad readability and duplicated docs pushing and codecov reporting.

Clean up travis.yml

---

scripts/prebuild-install.js
scripts/preinstall.js

This should help when debugging install failures.
Huge thanks to @rolftimmermans for adding this feature!

Better log messages for using external libzmq

---

package.json

Same error as #201, so we can merge #197

Fix nyc build failure

---

package.json

fix(package): update prebuild-install to version 4.0.0

---

.travis.yml
package.json

Can we have a new package to support node 10 please?

Node 10 support

---

package.json

This update is covered by semver but let's bump it anyway.
Closes #275

fix(package): update prebuild-install to version 5.2.0

---

lib/index.js
test/socket.messages.js
test/socket.zap.js
test/zap.js

Refs: https://github.com/nodejs/citgm/issues/605
Refs: https://nodejs.org/api/deprecations.html#deprecations_dep0005_buffer_constructor

Do not use the deprecated Buffer() constructor

---

.travis.yml
appveyor.yml
package.json

The `v8_enable_pointer_compression` failure seems to be fixed on Node 14
https://github.com/nodejs/node/pull/33688
https://github.com/prebuild/prebuild/issues/268#issuecomment-626274766
https://github.com/prebuild/prebuildify/issues/37

Use Node 14 + MSVC 2017

---

scripts/build_libzmq.sh
scripts/prepare.js

@aminya @captainsafia This PR fixes building from source.
We should add a test, but I'm not sure how to go about it.

Fix build from source

---

.idea/.gitignore
CONTRIBUTING.md
README.md

- Improve README readability
- Add a CONTRIBUTING page to add some technical basics about bindings, libraries, and tools
Put this together while troubleshooting the memory leak

Improve README and add a CONTRIBUTING page

---

.github/workflows/CI.yml
binding.gyp
package.json

Closes #515 
Closes #490 
Closes #495 
Closes #479  
Closes #475
Closes #473

fix: fix the openssl_fips error + fix: update dependencies

---

scripts/download.js

fix: random install failure

---

binding.gyp
script/build.ts

fix: use absolute paths for the action inputs

---

binding.gyp

fix: remove the inputs for the action

---

.github/workflows/CI.yml
script/build.ts

This brings many fixes from the libzmq library:
https://github.com/zeromq/libzmq/issues/4455
Fixes #533 
https://github.com/zeromq/libzmq/pull/4466

feat: upgrade libzmq to the latest dev version

---

.github/workflows/CI.yml
.npmrc
package.json
pnpm-lock.yaml
tsconfig.json

https://github.com/zeromq/zeromq.js/issues/529#issuecomment-1328184151

fix: fix the spawning errors in node-gyp-build

---

package.json

Updates the package to be able to build this package for windows 32bit
Upstream issue information here https://github.com/nodejs/node-addon-api/issues/1272

Update node-addon-api to v6

---

.github/workflows/CI.yml

ci: build on Windows server 2019 for more portability

---

.github/workflows/CI.yml
CMakeLists.txt
README.md
package.json
pnpm-lock.yaml
script/install.js

Fixes #667 
Fixes #668 
EmbeddedEnterprises/cmake-ts#27

fix: update cmake-ts's dependencies + fix installation failures in npm
