zeromq/zeromq.js

binding.gyp
instead of dll, which relies on users having the same libzmq in the same place, defeating some of the point.
Right now, this requires pkg-config to locate libzmq.a. Finding libzmq can be done with some manual checking as well, but if the goal is prebuilt binaries, requiring pkg-config should be okay.
=> statically link libzmq

.travis.yml, binding.gyp, test/util.js, test/zmq_proxy.push-pull.js, test/zmq_proxy.router-dealer.js, test/zmq_proxy.xpub-xsub.js, test/zmq_proxy.xrep-xreq.js
avoids need to bundle an extra library. This means zmq-prebuilt should always have curve support and no DLL dependencies.
Bummer: build settings for tweetnacl have never worked (should be fixed in libzmq-4.1.5), so this uses a prerelease of 4.1.5 from GitHub.
In order to get things passing on the OS X travis bot, I had to do some cleanup in a few tests that had loads of race conditions.
=> use tweetnacl for bundled nacl instead of libsodium

.gitignore, .travis.yml, binding.gyp, build_libzmq.sh
so it's reusable outside Travis
next step: run build_libzmq.sh as prepublish (or preinstall or whatever stage is the right one) prior to build on non-Windows, so it's always run automatically. I just don't know how to do the if-not-Windows part. I'll let someone with more js build experience figure that out.
=> make libzmq build stage a script

.gitignore
This works wonderfully!
Ran:
```
./build_libzmq.sh
prebuild
```
and it made the right prebuild! :tada:
Then I noticed some artifacts here for gitignoring.
=> git ignore build artifacts

package.json
This ugprade to `nan` addresses an issue where the `GCEpilogueCallback` type is not defined in the header files and causes a compilation error.
=> Upgrade nan native abstractions

package.json
A temporary fix for the fact that the preinstall script in npm is not guaranteed to run before install every time. This manifests itself up in the main nteract app when we try to use the enchannel-zmq-backend that relies on zmq-prebuilt.
=> Avoid using preinstall

build.js, package.json
dev installs need to run the build_zmq.sh script before `npm install`
users will rely on the prebuilt binaries we upload
=> install must rely only on prebuild

binding.gyp
Works the same way as OS X.
OpenBSD/FreeBSD seems a little more involved....
=> Add Linux static bindings

build_libzmq.sh
no longer need to use prerelease for tweetnacl support
(Windows not affected)
=> zmq 4.1.5 has been released

package.json
So, npm's `prepublish` doesn't run as one might expect in the lifecycle process. Namely, it can sometimes run before `npm install`.  For more details about this, you can check out some of the comments made by npm devs on [this issue](https://github.com/npm/npm/issues/3059).
This causes a problem for us because we want to be able to download and build the `libzmq` assets before we run the `install` that occurs only when publishing is done.
Enter the `in-publish` npm package which allows use to use the `in-publish` check in our `prepublish` script to confirm that we are indeed trying to publish the package, in which case we should pull the libzmq assets from the net and build them before moving on to our install step.
On the other end, if someone is installing the `zmq-prebuilt` package the …
=> Add in-publish to execute prepublish correctly

test/socket.monitor.js
Monitoring a closed socket was removed in https://github.com/JustinTulloss/zeromq.node/pull/540.
The `should use default interval and numOfEvents` test still times out randomly.
=> Fix monitoring test

appveyor.yml
Just messing around with appveyor.
Whats the difference between `x86` and `Win32`?
=> Enable Win32 build

README.md, appveyor.yml
Some tests are timing out randomly. This will retry the testsuite.
Since this is a upstream problem this is the best we can do for now (travis retries as well).
=> Retry tests on appveyor

binding.cc, binding.gyp, windows/include/zmq.h, windows/include/zmq_utils.h, windows/lib/Win32/libzmq.lib, windows/lib/x64/libzmq-v100-mt-4_0_4.dll, windows/lib/x64/libzmq-v100-mt-4_0_4.lib, windows/lib/x64/libzmq.lib, windows/lib/x86/libzmq-v100-mt-4_0_4.dll, windows/lib/x86/libzmq-v100-mt-4_0_4.lib
I added a static compiled version of zmq `v4.1.5`. It is linked (statically) in the `.gyp` file. I went ahead and also removed the DLL stuff inside the `bindings.cc` file.
The prebuilts will have a size of approx. 230 kB.
So this time I'm quite confident that the'll work though I didn't know how to test this without a release.
=> Windows prebuilts

package.json
We could even go with a shorter timeout since we use `travis/appveyor_retry`.
=> Reduce mocha timeout

.travis.yml
Travis CI will stop maintaining this image at the end of the month: https://blog.travis-ci.com/2016-10-04-osx-73-default-image-live/
=> Use default Travis OS X image

.travis.yml, scripts/publish_docs.sh
Bonus: We will see if the github token works after changing the repo name (#65) without needing to push a release.
=> Deploy docs on master

.travis.yml
It seems we don't need the `after_success` script for codecov. to work.
=> Travis: Fix docs and remove unnecessary script

.travis.yml, binding.gyp, codecov.yml, package.json
- Use codecov bash instead of codecov-node
- Bump OS X deployment target to 10.7, otherwise npm throws:
```
CXX(target) Release/obj.target/zmq/binding.o
clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
```
=> Add support for Node 7

build_libzmq.sh
This PR introduces two changes:
- Build libzmq with 2 cores only: I timed it [here](https://github.com/n-riesco/jp-kernel/pull/3#issuecomment-257561385) and it doesn't make sense to use more on a average machine.
- Remove libzmq source after build: This will reduce the package size by about 16.5 MB. I'm leaving the `.tar.gz` file so it doesn't have to be downloaded again on rebuilding (795KB).
/cc @rgbkrk @n-riesco
=> Reduce package size

build_libzmq.sh
I'll upgrade the windows libs on the bump to 4.2.0
=> Unix: Bump libzmq@4.1.6

.travis.yml, appveyor.yml, binding.gyp, build_libzmq.sh, package.json, scripts/build_libzmq.sh, scripts/download-win-lib.js, scripts/preinstall.js
General improvements to the install scripts:
- Use prebuild preinstall script to improve error logging. We don't need to trigger the buildscripts inside the gyp file anymore.
- Add rebuild script.
- Strip debug information from binaries to reduce their size.
=> Use prebuild preinstall script for building libzmq

binding.cc
I wrestled down some windows build warnings 😄 
The only warning I don't know how to fix is thrown [here](https://github.com/zeromq/zeromq.js/blob/master/binding.cc#L613):
```
c:\projects\zmq-prebuilt\node_modules\nan\nan_new.h(208): warning C4244: 'argument': conversion from 'int64_t' to 'double', possible loss of data (compiling source file ..\binding.cc) [C:\projects\zmq-prebuilt\build\zmq.vcxproj]
..\binding.cc(613): note: see reference to function template instantiation 'v8::Local<v8::Number> Nan::New<v8::Number,T>(A0)' being compiled
with
[
T=int64_t,
A0=int64_t
]
..\binding.cc(667): note: see reference to function template instantiation 'v8::Local<v8::Value> zmq::Socket::GetSockOpt<int64_t>(int)' being compiled
c:\projects\zmq-prebuilt\node_modules\nan\nan_new.h(208): warning C4244: …
```
=> Fix Nan type missmatch warnings

binding.cc, binding.gyp, codecov.yml, scripts/build_libzmq.sh, scripts/download-zmq.js, scripts/download.js, scripts/preinstall.js, test/socket.router.js, windows/include/zmq.h, windows/include/zmq_utils.h
This also simplifies the build script and move the essential stuff to cross platform js.
It will  make it possible to build libzmq from source on windows if someone writes a batch script handling the build.
=> Upgrade libzmq 4.2.0

package.json
This version is required to correctly build `zeromq`.
=> Bump prebuild@4.4.0

scripts/preinstall.js
ES6 isn't supported in older Node versions.
=> Use ES5 in preinstall script

package.json, scripts/build_libzmq.sh, scripts/preinstall.js
Skip compilation of libzmq if already built. This will speed up subsequent builds.
/cc @n-riesco
=> Don't recompile libzmq if already built

scripts/build_libzmq.sh
This doesn't fully fix https://github.com/nteract/nteract/issues/1189 since we are now running into the same issue in the libzmq build script.
=> Fix issue if path contains spaces

scripts/build_libzmq.sh
* From
https://github.com/nteract/nteract/issues/1189#issuecomment-260534970
* See
https://github.com/zeromq/libzmq/commit/7129187f877317fe6af8a5ece3638782ceb0d602
=> scripts: Fixes deprecated use of `--with-relaxed`

binding.cc
Fixes https://github.com/nteract/hydrogen/issues/515
(needs testing since I can't reproduce the issue in Hydrogen)
=> Socket::Socket: Don't throw a C++ exception

binding.cc
This PR removes the remaining `throw std::runtime_error(ErrorMessage());` in `binding.cc`.
Re: https://github.com/zeromq/zeromq.js/pull/104
=> binding.cc: Don't throw cpp exceptions

binding.gyp, scripts/build_libzmq.sh
Thanks to @minrk https://github.com/zeromq/libzmq/issues/2175#issuecomment-263225619, I noticed we only set `MACOSX_DEPLOYMENT_TARGET` in the gyp build and not for building libzmq it self.
I tried to stick with `MACOSX_DEPLOYMENT_TARGET=10.7` but this throws an error on macOS:
```
dyld: lazy symbol binding failed: Symbol not found: __ZNSsC1Ev
Referenced from: /Users/lukasgeiger/code/zmq-prebuilt/build/Release/zmq.node
Expected in: flat namespace
dyld: Symbol not found: __ZNSsC1Ev
Referenced from: /Users/lukasgeiger/code/zmq-prebuilt/build/Release/zmq.node
Expected in: flat namespace
```
`MACOSX_DEPLOYMENT_TARGET=10.9` is the minimal target that works on my macOS 10.12 machine.
/cc @rgbkrk
=> Set MACOSX_DEPLOYMENT_TARGET=10.9 for libzmq build

README.md, package.json, scripts/trigger_travis_build.sh
A new CI build will be triggered automatically given the environment variable `$TRAVIS_TOKEN` is set: https://github.com/zeromq/zeromq.js/tree/prebuilt-testing
=> Trigger tests of prebuilts on postpublish

package.json
This will reduce the overall package size by 10MB!
I'm using `@lgeiger/prebuild-install` since https://github.com/mafintosh/prebuild-install/pull/19 isn't merged yet.
=> Use prebuild-install to reduce package size

package.json
`prebuild-install@2.0.1` Didn't correctly handle `--target` and `--runtime`. This broke downloading for electron.
=> Bump prebuild-install@2.0.2

scripts/preinstall.js
This brings the new binaries compiled with TweetNacl, which fixes everything I was asking in comments of the issue #102.
=> Upgraded preinstall script for new ZMQ 4.2.2 windows binaries

README.md, scripts/build_libzmq.sh
Hello,
I made minor changes in build_libzmq.sh, which solves the cross compiling problem from #125 
Also, added documentation on how to use it.
=> cross compiling support #125

.travis.yml
Who expected Travis-CI to use sh, when in the rest bash is used...
=> Fix deploy script, as Travis-CI is using sh instead of bash

package-lock.json
Update `package-lock.json` to the new version created by npm 5.1, which has the new `"requires"` field. As this field is optional, the new `package-lock.json` is backwards compatible.
=> Update to npm 5.1

README.md, binding.gyp, package.json, scripts/prebuild-install.js, scripts/preinstall.js
Currently the only option to use these bindings is with a (prebuilt) binary that statically links zmq.
On our systems we prefer to use dynamic linking because our OS images already contain libzmq. This patch introduces an option (disabled by default) that allows using libzmq shared library if it has already been installed.
`npm install --zmq-external`
Or alternatively (with another package manager for example):
`npm_config_zmq_external=true yarn install`
In addition to changing how the bindings are linked; downloading prebuilt binaries and building the static library will be skipped if this option is enabled.
=> Allow building with libzmq shared library

binding.cc
Currently it is required to call `socket.unmonitor()` before a monitored socket goes out of scope.
The monitoring socket is never released, which causes the monitoring socket to stay around indefinitely. This causes a memory leak and a file descriptor leak. The latter causes the process to run out of file descriptors eventually.
I don't think it should be required to call `unmonitor()` before a socket is gc'ed – maybe it's not even feasible to always do this (depends on the application I guess).
This simple change calls `Socket::Unmonitor()` internally in the destructor. This is safe because `Socket::Unmonitor()` already checks to see if a socket is monitored, and is a no-op if it wasn't.
Not really sure if this requires any new tests. I wouldn't know how to write a unit test for this, …
=> Avoid leaking file descriptors and memory for monitored sockets

binding.cc
I'm sending relatively large messages with zeromq and noticed in the internals that there was an opportunity for using zeromq's zero-copy message initialisation on send.
Apparently this has been attempted before in the past, but is no longer used, and is annotated with the following comment:
> zero-copy version, but doesn't properly pin buffer and so has GC issues
I don't know what is meant by "pinning a buffer", but there was indeed a bug in the zero-copy implementation – it did not call `uv_close` for the allocated `uv_async_t`. Also, the implementation was in the (now unused) `Socket::Send` method.
This PR changes the following:
- Get rid of unused `Socket::Send`
- Reinstate zero-copy implementation with bugfix that calls `uv_close` when the outgoing message is released
- Apply …
=> Zero copy message sending

lib/index.js, test/socket.js
In my code I have found it useful to be able to determine if a socket is closed. This is information is already kept in a `state` variable in the C++ bindings, but not exposed as public API.
This PR proposes to add a `socket.closed` getter, which returns a boolean.
(An alternative implementation would be a `socket.state` getter which returns the socket's internal state. Which state values are possible would not be immediately obvious to me, so I'm proposing this boolean getter instead.)
The background of being able to check if a socket is closed is that some monitor events (and other events in my application) can occur slightly out of order due to timing issues native to how Node works. As such it is nice to avoid calling `socket.send()` or something similar if the socket was already …
=> Add getter for socket closed state

scripts/build_libzmq.sh, scripts/preinstall.js
* Added flag `-m32` when arch is `ia32`.
Fixes #214
=> scripts: fix build against node-x86

README.md
Just a simple change to the README so you can tell you're at the js lib at quick glance.
=> showcase the .js of zeromq.js at top of the readme

lib/index.js
Fixes issue #207 
When another message should be sent on a socket due to a pending reply,
which was not read yet, the message to be sent is put back in the queue.
As the read is already performed before that, nothing triggers a new flush_writes.
This makes `flushReads` asynchronous.
I think an alternative would be to invoke `flushWrites` in https://github.com/zeromq/zeromq.js/blob/26eecdc43d5a67b35475795aeb59f2e19d165ec5/lib/index.js#L701 asynchronously.
=> Fix failing send when socket not ready

package.json
Also changed our tagline / description for the package.json. I'd like to get 4.7.0 out. 
Went ahead and upgraded the version of prebuild-install while I was at it. I think that's _most_ of the maintenance level tasks that are needed here.
Closes #263
=> align our required version to the current LTS+

lib/index.js
This is to solve [issue 277](https://github.com/zeromq/zeromq.js/issues/277)
Basically just reused existing [fix for xpub/xsub proxy](https://github.com/JustinTulloss/zeromq.node/pull/593/commits/2c0ac29e5c96e5d3a41e6d145237ca079009f549)
=> Keep multipart messages in router/dealer proxy

binding.cc
I was looking for a memory leak in an application that creates lots of short lived monitored sockets. Running valgrind against the application showed that the `uv_timer_t` used to monitor sockets is never deleted.
This is a section of the valgrind output after running the application for an hour.
```
==27487== 2,491,736 bytes in 16,393 blocks are possibly lost in loss record 1,514 of 1,518
==27487==    at 0x4C2E19F: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==27487==    by 0xAE2354F: zmq::Socket::Monitor(Nan::FunctionCallbackInfo<v8::Value> const&) (binding.cc:1058)
==27487==    by 0xAE1F0BB: Nan::imp::FunctionCallbackWrapper(v8::FunctionCallbackInfo<v8::Value> const&) (nan_callbacks_12_inl.h:174)
```
`binding.cc` line 1058 was the line with `new …
=> Delete uv_timer_t when unmonitoring socket

README.md
nteract now has a monorepo package.json at root. Changed the link to the relevant package.json:
https://github.com/nteract/nteract/blob/master/applications/desktop/package.json
=> Link to the electron nteract application

.travis.yml
Add Node.js 11 test so we can publish a new release to support the v67 prebuild binaries.
=> Add Node.js 11 test

package.json
It looks like the latest release included broken prebuilt binaries due to a version conflict between Node and Electron. See https://github.com/prebuild/prebuild/pull/261 and https://github.com/prebuild/prebuild/issues/249
The upgrade hopefully fixes #338
Note I made the PR against the `5.x` to not conflict with #343
=> Upgrade prebuild

package.json
Electron v7 was just released. Unfortunately this makes the zeromq build fail, so the last patch release didn't build on CI. This pins the version of `node-abi` so the Electron v7 build is ignored.
=> Pin node-abi to not build for Electron v7

.travis.yml, binding.cc
As mentioned in #346, this library fails to install with Node 13.0.1, due to compilation errors.
After a quick investigation, the issue seems to be
```c++
v8::Local<v8::Value> v8::Object::Get(uint32_t index)
``` 
which [has already been deprecated for a while](https://v8docs.nodesource.com/node-12.0/db/d85/classv8_1_1_object.html#af8c3c8fa1256e7ea440616e82b461d31) and seems to have been removed in favour of
```c++
v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context> context, uint32_t index)
```
in Node 13 / V8 7.8.
This seems to fix the issue.
It's only been tested with Node 12.13.0 and 13.0.1, on Windows.
This might break compatibility with older versions of Node, however [the new method was already present](https://v8docs.nodesource.com/node-6.17/db/d85/classv8_1_1_object.htm …
=> Added support for Node 13

package.json
#348 added support for Node 13 and Electron v7 so we don't need to pin `node-abi` anymore.
This reverts #345
=> Revert "Pin node-abi to not build for Electron v7"

binding.gyp, package.json
=> Build zeroMq v5 on Electron 9 - Windows

.travis.yml, appveyor.yml
Travis and Appveyor failed to upload the prebuilds to the GitHub tag.
https://github.com/zeromq/zeromq.js/releases/tag/v5.2.1
Previous failures:
https://ci.appveyor.com/project/zeromq/zeromq-js/builds/38706697
https://travis-ci.org/github/zeromq/zeromq.js/builds/767078872
=> Fix uploading of prebuilds to the GitHub tag

appveyor.yml
Prebuilds are being produced but looks like the GH token is outdated.
=> Update GITHUB_TOKEN for artifact upload

.github/workflows/CI.yml, binding.gyp, package.json
This fixes the fallback when no prebuild is provided
=> Call prepare from node-gyp using actions

package.json
It seems that GitHub Actions is failing to upload the artifacts correctly if the size is larger than some amount. This replaces `prebuildify --all` with a selection of the versions. We had this issue in the previous release, which caused the prebuilds to be faulty.
`prebuildify --all` produced 29 prebuilds for all the versions, but now only 10 of them are selected. For the other versions, the build will happen from the source automatically.
https://github.com/actions/upload-artifact/issues/190
=> Prebuildify only a selection of the versions to reduce size

binding.cc, package.json
=> Context aware

.github/workflows/CI.yml, .mocharc.js, README.md, binding.gyp, package.json, pnpm-lock.yaml, script/build.ts, script/prebuild.ts, test/unit/compat/socket-zap-test.js, test/unit/helpers.ts, test/unit/socket-close-test.ts, test/unit/socket-send-receive-test.ts
Fixes #477
Fixes #489 
Fixes #441 
Fixes #523 
Fixes #462 
Fixes #507
Fixes #384
=> feat: improve the architecture handling the build system + add support for MacOS Arm + Windows 32 bit

.github/workflows/CI.yml, script/macos-arm-deps.sh
=> fix: make macos-arm-deps.sh executable + fix paths + fix re-running

.github/workflows/CI.yml, script/macos-arm-deps.sh
https://github.com/zeromq/zeromq.js/issues/529
=> fix: install arm brew on MacOS Arm to install libsodium

.gitignore, src/incoming_msg.cc, src/util/electron_helper.h
This way, no separate build for NodeJS and Electron v21(+) is needed.
Cache the result once, to not have to look up the value on each incoming message.
=> Fix: Detect Electron version at runtime

.github/workflows/CI.yml
https://github.com/zeromq/zeromq.js/issues/529#issuecomment-1588787771
=> ci: build on Ubuntu 20.04

binding.gyp, script/build.ts
Use TweetNacl, which doesn't need a (user having) libsodium installed.
As discussed here: https://github.com/zeromq/zeromq.js/issues/529#issuecomment-1370721089 , libzmq doesn't handle statically linking `libsodium`.
I think the best, and most versatile option (keeping in mind all build platforms: Unix, Alpine, macOS x64, macOS ARM, Windows x64, Windows ARM, ...), as a next step, to build libsodium ourselves in the build.ts, before `libzmq` itself. Preferably with `libsodium-cmake` (https://github.com/robinlinden/libsodium-cmake) .
=> Fix: Remove libsodium dependency (for now).

.github/workflows/CI.yml, .gitignore, package.json, pnpm-lock.yaml
https://github.com/zeromq/zeromq.js/pull/554 was merged recently which finally fixes zeromq.js v6 in the Node.js LTS (v20) environment, however the CI prebuilds are not working and pipelines getting failed. That's because dependency tree and CI environment is outdated for a recent Node.js v20. This PR updates zeromq.js's dependencies and CI environment to meet latest requirements. 
There are still a lot of tests that needs to be fixed though, which I did not try to do.
Successful prebuilds action can be seen here: https://github.com/pshenmic/zeromq.js/actions/runs/689396918
* Added node-gyp 10.0.1 override (fixes deprecated distutils)
* Upgraded CI Node.js version to v20
* Upgraded PNPM to 8
* Upgraded MacOS runner to 13 Ventura (fixes macOS prebuilds)
* Upgraded `node-addon-api` (fixes …
=> fix: update node-addon-api, node-gyp, and node

README.md
Previously, this link in the readme was giving me a 404 not found
=> docs: Fix link to API docs

script/build.ts
This fixes the build with newer platforms and compilers. It also includes other fixes from libzmq
=> fix: update libzmq to the latest version

.github/workflows/CI.yml, script/macos-arm-deps.sh
=> ci: use ARM64 Macos 14 runner for ARM builds

binding.gyp
~`CMAKE_OSX_ARCHITECTURES` is already set in `build.js`, so there's no need to set it in `binding.gyp`.~ In fact, if the architecture is inferred from the host (and not via the `$ARCH` env var), this previously resulted in incorrect cross-compiling.
Fixes #632
=> Remove cross-compilation arch flags for MacOS

.github/workflows/CI.yml, .github/workflows/docs.yml
=> bump ci actions versions

package.json, pnpm-lock.yaml
The install script runs on the user machine, and at that point, the JavaScript files are already included in the package
=> fix: reduce production build dependencies

package.json, tsconfig.json
Newer npm/yarn versions don't populate `process.env.npm_config_argv` resulting in `npm/yarn` installs hanging. This fixes the issue
https://github.com/prebuild/node-gyp-build/blob/464e3881600de2107f35fd1c55afff232a768123/bin.js#L75
Fixes #644
Fixes #647 
Fixes #646
=> fix: specify build_from_source using env vars

.gitignore, package.json, script/build.js, script/prebuild.mjs, script/utils.js
Fixes #647 
Fixes #643 
Fixes #651 
Closes #650
=> fix: make postinstall script production specific + check in build script dists

.github/workflows/docs.yml, CMakeLists.txt, README.md, src/draft.ts, src/module.h, src/outgoing_msg.cc, src/socket.cc, src/socket.h, src/util/arguments.h, src/util/string_or_buffer.h
=> feat: fix and enable Zeromq Draft API support

.github/workflows/CI.yml, docker/debian.dockerfile, script/install-deps.bash, script/install-deps.sh
Fixes #564 
Fixes #590 
Fixes #579 
Fixes #560 
Fixes #332 
Fixes #582
=> ci: add support for arm64 Linux

.github/workflows/CI.yml, CMakeLists.txt, package.json, script/install-deps.sh, vcpkg.json
Fixes https://github.com/zeromq/zeromq.js/issues/710
=> ci: build Linux Arm64 binaries on Ubuntu 20 - update vcpkg baseline

src/module.h
The new MSVC headers don't expose the chrono_literals unless chrono is included.
=> fix: add missing include for chrono on Windows

package.json, pnpm-lock.yaml
This changes the parent directory name from `abi` to `libc-abi-buildType` to prevent conflicts when all the binaries are copied for zeromq to the same directory.
This caused glibc and musl binaries to conflict in the previous release on arm64
Fixes #718 
Related to #715
=> fix: prevent conflict between binaries

README.md
Referring past [commit](https://github.com/zeromq/zeromq.js/commit/55b906bb201a139628247ed9a213c5b5b82c2d55)
=> docs: update reference link
